name: cascade_view
description: "Select from a set of related data sets, such as provinces, municipalities, company levels, classifications of things, etc."
version: 0.1.3
homepage: "https://github.com/TroubleChenC/cascade_view"

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
